# Setup
title:               SADMIN
tagline:             'Unix System ADMINistrator Tools'
description:         'SADMIN Tools'
url:                 ''
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jacques Duplessis
  url:               https://twitter.com/sadm_linux
  email:             support@sadmin.ca

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             2.3.1
google_analytics_id: #UA-XXXX-Y
